package com.ding.luna.ext;

public class Example {

    public static String get() {
        StringBuilder sb = new StringBuilder();
        sb.append("###########################################################\n");
        sb.append("#\n");
        sb.append("# 文件第一个非空白行填写国家 (日亚填日本，德亚填德国)\n");
        sb.append("#\n");
        sb.append("###########################################################\n");
        sb.append("\n");
        sb.append("日本\n");
        sb.append("\n");
        sb.append("###########################################################\n");
        sb.append("#\n");
        sb.append("# 1. 地址区列出所有可选的地址，地址之间用空行分隔。\n");
        sb.append("#\n");
        sb.append("# 2. 地址对应着亚马逊网站填写地址的顺序，行与行对应，\n");
        sb.append("#    留空的行用一个'-'号表示。\n");
        sb.append("#\n");
        sb.append("# 3. 行中如果包含'{}'，软件会自动替换成一个4位的随\n");
        sb.append("#    机数字串，如“0125”。\n");
        sb.append("#\n");
        sb.append("###########################################################\n");
        sb.append("\n");
        sb.append("**地址区开始**\n");
        sb.append("\n");
        sb.append("Ma Yun\n");
        sb.append("278-0056\n");
        sb.append("千葉県\n");
        sb.append("野田市五木新田\n");
        sb.append("41-8-A-1紅い倉庫（{}-tyj）\n");
        sb.append("株式会社アイデイアーアイデイアー\n");
        sb.append("0480536401\n");
        sb.append("\n");
        sb.append("Yun Ma-{}\n");
        sb.append("152-0034\n");
        sb.append("東京都\n");
        sb.append("目黒区緑が丘\n");
        sb.append("-\n");
        sb.append("宝冢映画株式会社\n");
        sb.append("9012345678\n");
        sb.append("\n");
        sb.append("**地址区结束**\n\n");
        sb.append("###########################################################\n");
        sb.append("#\n");
        sb.append("# 1. 信用卡区列出所有可选的卡，卡与卡之间用空行分隔。\n");
        sb.append("#\n");
        sb.append("# 2. 信用卡格式按照“卡种->卡号->姓名->到期时间”的\n");
        sb.append("#    顺序，一行行填写。\n");
        sb.append("#\n");
        sb.append("# 3. 注意要写对卡种名称；到期时间格式为“月份/年份”。\n");
        sb.append("#\n");
        sb.append("###########################################################\n");
        sb.append("\n");
        sb.append("**信用卡区开始**\n");
        sb.append("\n");
        sb.append("Visa\n");
        sb.append("4013540108580582\n");
        sb.append("WANG XIAOHONG\n");
        sb.append("01/2019\n");
        sb.append("\n");
        sb.append("MasterCard\n");
        sb.append("5110237120075001\n");
        sb.append("ZHANG QIANG\n");
        sb.append("05/2020\n");
        sb.append("\n");
        sb.append("American Express\n");
        sb.append("376833817365851\n");
        sb.append("LI LEI\n");
        sb.append("03/2017\n");
        sb.append("\n");
        sb.append("JCB\n");
        sb.append("3582401116302134\n");
        sb.append("HAN MEIMEI\n");
        sb.append("01/2018\n");
        sb.append("\n");
        sb.append("DinersClub\n");
        sb.append("31408186254247\n");
        sb.append("JASON BOURNE\n");
        sb.append("12/2019\n");
        sb.append("\n");
        sb.append("**信用卡区结束**\n\n");
        sb.append("###########################################################\n");
        sb.append("#\n");
        sb.append("# 1. 账号区列出所有待注册的账号，账号之间不需要空行。\n");
        sb.append("#\n");
        sb.append("# 2. 账号格式为“邮箱 密码 姓名”, 其中姓名不填的话，\n");
        sb.append("#    软件会随机生成一个。\n");
        sb.append("#\n");
        sb.append("# 3. 姓名中如果包含‘{}’，软件会自动替换成一个4位的随\n");
        sb.append("#    机数字串，如“8729”。\n");
        sb.append("#\n");
        sb.append("###########################################################\n");
        sb.append("\n");
        sb.append("**账号区开始**\n");
        sb.append("\n");
        sb.append("heguangtang4001@gmail.com q123456\n");
        sb.append("heguangtang4002@gmail.com q123456\n");
        sb.append("heguangtang4003@gmail.com q123456\n");
        sb.append("heguangtang4004@gmail.com q123456 马小田{}\n");
        sb.append("heguangtang4005@gmail.com q123456 Li Lei\n");
        sb.append("\n");
        sb.append("**账号区结束**");
        return sb.toString().replace("\n", System.lineSeparator());
    }

}
